language: python
matrix:
  include:
    - python: 3.7
      arch: arm64
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=py37
install:
    - pip install tox-travis
script:
    - travis_retry tox
