language: python
matrix:
  include:
    - python: 3.8
      arch: arm64
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=py38
install:
    - pip install tox-travis
script:
    - travis_retry tox
